// El arreglo completo: al cerrarse la época, el miembro debe poder RECUPERAR su parte no vendida.
import { initSimnet } from "@stacks/clarinet-sdk";
import { Cl, cvToValue, cvToString } from "@stacks/transactions";
const simnet = await initSimnet("Clarinet-jing-buy-stx-market-spread.toml");
const A = simnet.getAccounts(); const D = A.get("deployer"); const w = [...A.values()];
const [alice, bob, taker, carol] = [w[1], w[2], w[3], w[4]];
const R = "jing-buy-stx-market-spread", E = Cl.buffer(new Uint8Array(0));
const call = (fn, args, who) => cvToString(simnet.callPublicFn(R, fn, args, who).result);
const S = () => { const s = cvToValue(simnet.callReadOnlyFn(R, "get-state", [], D).result); const o = {}; for (const k of ["epoch","total-shares","unfilled-index","held-sats","resting"]) o[k] = BigInt(s[k].value); return o; };
const fmt = (o) => Object.entries(o).map(([k,v]) => `${k}=${v}`).join(" ");
const sbtc = (who) => cvToValue(simnet.callReadOnlyFn("mock-ft", "get-balance", [Cl.principal(who)], D).result).value;
const take = (ustx) => call("rv-take", [Cl.uint(ustx), Cl.uint(15999)], taker);
const sellTo = (target) => { let step = 50000000n; for (let i = 0; i < 400; i++) { const r = S().resting; if (r <= target*13n/10n) return; const gap = r - target; const want = gap < step ? gap : step; if (!take(want*3200n).startsWith("(ok")) { step = step/2n; if (step < 1n) return; } } };
console.log("Alice deposita 1e8:", call("deposit", [Cl.uint(100000000), E], alice).slice(0,40));
sellTo(400n); console.log(fmt(S()));
console.log("Bob deposita 1e7:", call("deposit", [Cl.uint(10000000), E], bob).slice(0,60));
const antes = BigInt(sbtc(bob));
const before = S().resting;
console.log("un comprador se lleva ~80%:", take(before*8n/10n*3200n), fmt(S()));
console.log("posición de Bob:", cvToString(simnet.callReadOnlyFn(R, "get-position", [Cl.principal(bob)], D).result));
console.log("Bob reclama (claim):", call("claim", [], bob));
const despues = BigInt(sbtc(bob));
console.log(`sBTC devuelto a Bob al reclamar: ${despues - antes} sats  <-- antes del arreglo era 0`);
console.log("estado final:", fmt(S()));
